#!/usr/bin/env bash
# Provision the global RubyGems CLI tools against Homebrew Ruby.
# run_onchange_: re-runs whenever this file changes (e.g. when GEMS is edited).
# shellcheck disable=SC2034

set -euo pipefail

readonly SCRIPT_NAME="$(basename "${BASH_SOURCE[0]}")"

# run_onchange_ scripts execute from a temp dir, so source from the installed path
source "$HOME/.setup/lib/common.sh"

if ! command -v brew &>/dev/null; then
  log_error "brew not found on PATH; skipping RubyGems provisioning"
  exit 0
fi

readonly RUBY_PREFIX="$(brew --prefix ruby 2>/dev/null || true)"
if [[ -z "$RUBY_PREFIX" ]] || [[ ! -x "$RUBY_PREFIX/bin/gem" ]]; then
  log_error "Homebrew ruby not installed; run ~/.setup/tools_macos.sh first"
  exit 0
fi

# Gems live outside the Cellar so `brew upgrade ruby` cannot delete them.
readonly GEM_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/gem"
readonly BIN_DIR="$HOME/.local/bin"

# Global CLI tools installed as gems. Editing this list re-triggers the script.
readonly GEMS=(
  git-status-tree
)

log_info "Installing ${#GEMS[@]} gem(s) into ${GEM_ROOT}..."
for gem in "${GEMS[@]}"; do
  GEM_HOME="$GEM_ROOT" "$RUBY_PREFIX/bin/gem" install "$gem" --no-document --quiet
done

# RubyGems binstubs resolve their own gem through GEM_HOME, which is not exported
# globally, so a bare symlink into ~/.local/bin would fail at runtime. Ship a
# wrapper that sets GEM_HOME and execs the binstub instead.
mkdir -p "$BIN_DIR"
for binstub in "$GEM_ROOT"/bin/*; do
  [[ -x "$binstub" ]] || continue
  wrapper="$BIN_DIR/$(basename "$binstub")"
  cat >"$wrapper" <<EOF
#!/bin/sh
# Generated by setup_ruby_gems.sh - do not edit.
GEM_HOME="${GEM_ROOT}"
export GEM_HOME
exec "${binstub}" "\$@"
EOF
  chmod +x "$wrapper"
done

# git-status-tree's extconf.rb hook shells out to bin/git_add_alias_tree on every
# install, writing an `alias.tree` pinned to a versioned gem path plus a
# [status-tree] section into the global gitconfig. That file is a symlink into
# the chezmoi-managed dot_config/git/gitconfig.tmpl, so undo the hook and let the
# template's `st` alias stay authoritative.
git config --global --unset alias.tree 2>/dev/null || true
git config --global --remove-section status-tree 2>/dev/null || true

log_success "RubyGems toolchain ready"
